### ISSUE TITLE
QueueTrended Error - vector length

### ISSUE THREAD

**Issue by engti** [randyzwitch/RSiteCatalyst#135] opened 2015-05-30 08:25 UTC
Hi,

First of all thank you so much for this useful package.

My issue is that when I make the following call:

```
 QueueTrended( rsid,"2015-03-02","2015-04-27","event43",c("eVar55","eVar5"),"day")
```

I get the following error:
Error in names(working.metrics) <- metrics : 
  'names' attribute [1] must be the same length as the vector [0]

@WillemPaling mentioned the same error at https://github.com/randyzwitch/RSiteCatalyst/issues/78

But that was for "selected" option. I am not too sure how to fix it for my use case?

Also, when I try to pass the selected option for eVar using a dataframe column it gives me an unboxing error.

Query [fin_usr$GUID is a dataframe that contains the values I want to select within eVar55]:
```
QueueTrended( rsid,"2015-03-02","2015-04-27","event43",c("eVar55","eVar5"),selected = list(eVar55=c(fin_usr$GUID)),"day")
```
I get the error:
Error: Tried to unbox a vector of length 86

Thanks.

**Comment by randyzwitch** [comment] 2015-05-31 13:23
For the first issue, would you be willing to run in debug mode and send the JSON file? Like the issue you referenced, and #134 currently open, it's hard for me to reproduce this error locally. But if I had an example, maybe I could fix it once and for all.

To run in debug mode, you just do:
```R
SCAuth("<name>", "key", debug.mode = TRUE)
```

This will create text files of all of the steps, so that I can see what Adobe is returning from the API, which will help me figure out where I'm trying to rename something that doesn't exist.

For your second problem, you just need to pass your values like:

```R
selected = c("www:home","www:search","www:about")
```

You don't need the `selected = list(eVar55=c(fin_usr$GUID))`, I think just `selected = fin_usr$GUID` should work

**Comment by engti** [comment] 2015-06-01 12:01
Thanks so much for your response Randy.

While running it in debug mode I got the following output:

```
[1] "Requesting URL:  https://api2.omniture.com/admin/1.4/rest/?method=Report.Validate"
{"reportDescription":{"dateFrom":"2015-03-02","dateTo":"2015-04-27","reportSuiteID":"REPORTSUITE-REDACTED","dateGranularity":"day","metrics":[{"id":"event43"}],"elements":[{"id":"eVar55","top":"day","startingWith":0},{"id":"eVar5"}]}} 
[1] "DEBUG: saving output as PostRequest_1433159884.93527.json"
[1] "Requesting URL:  https://api2.omniture.com/admin/1.4/rest/?method=Report.Queue"
{"reportDescription":{"dateFrom":"2015-03-02","dateTo":"2015-04-27","reportSuiteID":"REPORTSUITE-REDACTED","dateGranularity":"day","metrics":[{"id":"event43"}],"elements":[{"id":"eVar55","top":"day","startingWith":0},{"id":"eVar5"}]}} 
[1] "DEBUG: saving output as PostRequest_1433159891.62027.json"
[1] "Requesting URL:  https://api2.omniture.com/admin/1.4/rest/?method=Report.Get"
{"reportID":355884781} 
[1] "Requesting URL attempt #1"
[1] "Requesting URL attempt #2"
[1] "Requesting URL attempt #3"
[1] "DEBUG: saving output as PostRequest_1433159917.60827.json"
[1] "Received trended report."
Error in names(working.metrics) <- metrics : 
  'names' attribute [1] must be the same length as the vector [0]
```

Was wondering what would be the best way to share the output JSON files with you?

Regards,

Robin

**Comment by randyzwitch** [comment] 2015-06-01 12:40
You can email it to me at rzwitch+rsitecatalyst@gmail.com

**Comment by engti** [comment] 2015-06-14 16:52
Hi Randy,

I was wondering if there were any updates on this front.

Cheers.

**Comment by randyzwitch** [comment] 2015-06-15 00:50
I certainly have tried, but unfortunately, I don't have a solution yet. This error arises in one of the few parts of the code I don't understand, which was originally written by @WillemPaling.

At one point, all of these tests worked, but now they also seem to be failing, so something else is broken as well:

```R
library("RSiteCatalyst")
library(testthat)

SCAuth("rzwitch:ZwitchCorp", "aff50a589d1abd70c3d0f02fa3e9592f", debug.mode = TRUE)

overtime2 <- QueueOvertime("zwitchdev",
                           date.from = "2014-09-01",
                           date.to = "2014-10-20",
                           metrics = c("pageviews", "visits", "bounces"),
                           date.granularity = "day",
                           segment.id = c("5433e4e6e4b02df70be4ac63", "54adfe3de4b02df70be5ea08"),
                           anomaly.detection = TRUE,
                           interval.seconds = 10,
                           max.attempts = 20)

overtime3 <- QueueOvertime("zwitchdev",
                           date.from = "2014-09-01",
                           date.to = "2014-10-20",
                           metrics = c("pageviews", "visits", "bounces"),
                           date.granularity = "day",
                           anomaly.detection = TRUE,
                           interval.seconds = 10,
                           max.attempts = 20)

evars <- GetEvars("zwitchdev")

test <- QueueTrended("zwitchdev",
             "2015-03-02",
             "2015-04-27",
             "pageviews",
             c("eVar1","eVar2"),
             "day")




###################

reportsuite <- "dev"

ranked1 <- QueueRanked(reportsuite, 
                       date.from = "2014-04-01", 
                       date.to = "2014-04-20", 
                       metrics = "pageviews", 
                       elements = c("page") 
)

ranked2 <- QueueRanked(reportsuite, 
                       date.from = "2014-04-01", 
                       date.to = "2014-04-20", 
                       metrics = "pageviews", 
                       elements = c("page", "sitesection") 
)

ranked3 <- QueueRanked(reportsuite, 
                       date.from = "2014-04-01", 
                       date.to = "2014-04-20", 
                       metrics = "pageviews", 
                       elements = c("page", "sitesection", "browser") 
)

trended1 <- QueueTrended(reportsuite, 
                         date.from = "2014-04-01", 
                         date.to = "2014-04-20", 
                         metrics = c("pageviews","visits"), 
                         elements = c("sitesection") 
)

trended2 <- QueueTrended(reportsuite, 
                         date.from = "2014-04-01", 
                         date.to = "2014-04-20", 
                         metrics = "pageviews", 
                         elements = c("sitesection", "page") 
)

trended3 <- QueueTrended(reportsuite, 
                         date.from = "2014-04-01", 
                         date.to = "2014-04-02", 
                         metrics = "pageviews", 
                         elements = c("sitesection", "page","browser") 
)

```

**Comment by randyzwitch** [comment] 2015-06-15 01:15
Going through all the old versions of the package on CRAN suggests that this never worked (or newer version of a package dependency broke something). Much bigger deal than I imagined.

**Comment by WillemPaling** [comment] 2015-06-15 12:59
Do we have a good idea of what causes this yet? It'd be great if we could write a test case that reliably triggers it.

I've been in touch with @engti on Twitter, and I'm going to take a look and see if I can work out what's happening. I assume it is sitting somewhere in that recursive function.

**Comment by randyzwitch** [comment] 2015-06-15 15:27
Well, none of the tests above work on my computer, so that's a good starting point :)

The problem is right here:
https://github.com/randyzwitch/RSiteCatalyst/blob/master/R/BuildInnerBreakdownsRecursively.R#L59

I just don't know why that the vector length would be zero. Could this be part of the off-by-one error you fixed way way back (maybe a year ago?)

**Comment by WillemPaling** [comment] 2015-06-16 01:50
I think I've got this resolved.

It seems that when you get to a bottom level breakdown, there can still be null rows within it, and this was tripping up the parser. This is most likely to occur when running a trended report with multiple elements.

I've committed the change in a new branch, but I haven't run the tests yet. I'll try to get to that in the next day or two.

@engti - can you try installing the NullBreakdownFix branch and see if it works for you?
https://github.com/randyzwitch/RSiteCatalyst/tree/NullBreakdownFix

```
install.packages("devtools")
library(devtools)
install_github("randyzwitch/RSiteCatalyst", ref="NullBreakdownFix")
```

**Comment by engti** [comment] 2015-06-16 05:17
Halleluijah Gentlemen..... a million thanks from the bottom of my heart. It works, I'll do more tests but I've pulled data using 2, 3 and 4 levels of breakdown. And they all seemed to work.

I've been developing a Shiny dashboard using data from SiteCatalyst and trying to sell it within my org, and this had been a major tripping point.  Once again, many many thanks not just for fixing it but also for simply looking into this.

**Comment by WillemPaling** [comment] 2015-06-16 05:21
@engti - great to hear. I'm glad it's finally sorted! I'll do some more tests and then submit a pull request for @randyzwitch.

**Comment by WillemPaling** [comment] 2015-06-16 05:28
@randyzwitch - on the tests above, the first one is failing for me due to the two segment IDs. The API only supports a single segment id: https://marketing.adobe.com/developer/documentation/sitecatalyst-reporting/r-reportdescription#reference_9ECD594AEDD240D7A475868824079F06

Some of the bottom ones were failing because the report suite was set to "dev" rather than "zwitchdev". I'm working through some others. It seems I'm still getting some instances of:

```
Error in names(working.metrics) <- metrics : 
  'names' attribute [1] must be the same length as the vector [0]
```

I think your dev report suite has some good sparse data when we do breakdowns, meaning it's quite prone to these null breakdowns that cause the errors.

I'll keep working through it.

**Comment by WillemPaling** [comment] 2015-06-16 05:48
It seems like sitesection is empty in most cases for your dev report suite. So that's why those tests give a lot of errors due to null breakdowns. Doesn't mean that they shouldn't be handled though.

I'll try to think through how they should be handled. 
@randyzwitch have you got any thoughts on this?

**Comment by WillemPaling** [comment] 2015-06-16 12:26
@randyzwitch - I've made some updates so all tests work and don't throw errors.
They are strange though - mostly it's due to sitesection not being populated, so the bottom level breakdowns are all nulls. 

I think that's really an issue with the API. If the elements of a row that is [page,sitesection], and page is home, and sitesection is null in all instances, then I think there should be a breakdown for [home,null] rather than no breakdown.

We could write a handler to say if there's a null breakdown, then we look at the parent, and create the null breakdown row (e.g. [home,null]) - but that seems like overkill.

We should probably put in some error/warning messaging to indicate that these null breakdowns were encountered, particularly if we return an empty data frame.

**Comment by randyzwitch** [comment] 2015-06-16 13:12
"on the tests above, the first one is failing for me due to the two segment IDs. The API only supports a single segment id: https://marketing.adobe.com/developer/documentation/sitecatalyst-reporting/r-reportdescription#reference_9ECD594AEDD240D7A475868824079F06"

Yeah, that's just some 'parent getting no sleep' copy-pasting. I didn't mean to post my API credentials either (they've since been changed, but if you want an account @WillemPaling let me know).

"I think that's really an issue with the API"

I agree. I would just throw a warning that the breakdown is null, and tell the user that the results may be unreliable. I have very little time to support this any more, so writing custom parsers for awkward JSON doesn't seem like a good use of time.

**Comment by WillemPaling** [comment] 2015-06-16 22:46
That sounds like the right approach to me. I think it's generally pretty rare, because production report suites aren't as sparse.

I'll update the messaging, run the tests, and submit a PR. Hopefully in the next few days.

On the API credentials - haha. It was useful for this instance, because it meant it was easy to reproduce. Might be useful for debugging in future, so we're working with the same data, but I think it's fine for now.

And feel free to give me a nudge like this if there is anything that needs working on. I don't get much time to look at RSiteCatalyst, or my github notifications, but I do use it in production, and can always find time.

**Comment by randyzwitch** [comment] 2015-06-24 12:15
Willem/@engti, are these changes stable enough to merge into master and send a new version to CRAN?

**Comment by WillemPaling** [comment] 2015-06-24 12:40
I still haven't updated the messaging for when you get a null breakdown. The changes are stable though, I've been using this version as my main version.

I'm moving house, in the next few days, so probably won't have time. But could get the messaging updated, and take a look at a more flexible approach to top sometime next week.

Want to wait until then? Or just get this fixed now, and deal with the messaging and top handling later?

**Comment by randyzwitch** [comment] 2015-06-24 21:00
It's no hurry for me, just figured I'd get it out there to avoid other people opening tickets ;)

So, whenever you get to it, good luck with your move!

**Comment by engti** [comment] 2015-06-30 09:09
hey @randyzwitch  apologies for not replying earlier. the changes have worked well for me, but i must say that the original issue concerned the sparsest report set i had. and since then i haven't faced any issues either in prop breakdown or in evar breakdown.

thanks again to the two of you :)

**Comment by randyzwitch** [comment] 2015-07-01 12:02
Great, thanks for confirming. We'll merge these changes in and get a new version of the package out.

**Comment by WillemPaling** [comment] 2015-07-02 00:47
I haven't had time to look at this yet. Let's just merge the changes and
I'll improve the messaging for a later version.

Are you happy with that approach? Let me know and I'll submit the PR.

Willem

**Comment by randyzwitch** [comment] 2015-07-02 01:08
Yeah, just merge it. What needs to be updated, the documentation?

**Comment by WillemPaling** [comment] 2015-07-02 02:11
Logging. To log a warning when a null breakdown is encountered and ignored.

**Comment by randyzwitch** [comment] 2015-07-09 14:04
Submitting 1.4.4 to CRAN today. We'll get the warnings sorted later (I'm creating a new testing issue, we'll take care of it there)

**Closed by randyzwitch** 2015-07-09 14:04 UTC
Labels: bug

**Comment by samistat08** [comment] 2017-08-09 15:49
Hello Guys; I have faced the same problem and getting this error while running ShinyApp. It seems you have already fixed it since it s been a long time. But when I try to install [install_github("randyzwitch/RSiteCatalyst", ref="NullBreakdownFix")](url), I get 

> Installation failed: 404: Not Found

my error is as following and I would be thankful if you guide me through it:
Warning: Error in <-: 'names' attribute [8] must be the same length as the vector [7]
Stack trace (innermost first):
    41: structure
    40: server [#7]
     4: <Anonymous>
     3: do.call
     2: print.shiny.appobj
     1: <Promise>
Error in attributes(.Data) <- c(attributes(.Data), attrib) : 
  'names' attribute [8] must be the same length as the vector [7]

**Comment by randyzwitch** [comment] 2017-08-09 16:43
Just to be clear, you had the error using the most up-to-date version of RSiteCatalyst (1.4.13) and then tried to install an older version? 

The branch you tried to install has been deleted, because it was merged into the main version of RSiteCatalyst. If you were using 1.4.13 and this behavior still exists, please create a new issue.
