### ISSUE TITLE
In if (segment.id != “”) { : the condition has length > 1 and only the first element will be used

### ISSUE THREAD

**Issue by blandinew** [randyzwitch/RSiteCatalyst#209] opened 2017-02-22 16:32 UTC
Hi,

I got started to work with R for a couple of weeks. I'm using the RSiteCatalyst-Package to get the data from Adobe.
I wrote a script, which is working, but today I just wanted to add a second segment (Segment:657e95e3e4b0d8e408b03fbb) in those script and now I'm getting following error message:
*Error: Tried to unbox a vector of length 2
In addition: Warning message:
In if (segment.id != "") { :
  the condition has length > 1 and only the first element will be used*

I wrote it like that and get the error:
MyFirstData <- QueueTrended("xxxxxx",
                             startdate,
                             enddate,
                             c(
                               "orders",
                               "revenue",
                               "visits"),
                             elements = c("mobiledevicetype"),
                             segment.id = c("s2213_67b1d377e4b0ca6c533db0da","**657e95e3e4b0d8e408b03fbb**"),
                             date.granularity = "day",
                             top = "100")

I already tried to find an answer to this problem but I could'nt find a solution. 
Do you have an idee how I can solve this problem? I need to consider the 2 segments
Please note: I'm a beginner :-)

Thanks in advance

**Comment by randyzwitch** [comment] 2017-02-24 14:07
Thanks for reporting this. The quick answer is, R is telling you that `segment.id` only takes a single input, not a vector of segments. 

The bigger question is whether this is implemented correctly on my end, or whether the Adobe API actually takes in multiple segments for that parameter. Unfortunately, I don't know that off the top of my head, so I'll need to research. The work-around would be to build a single segment that captures the behavior of both filters together, but that's obviously not a scalable solution if you plan to do this for numerous combinations.

**Comment by blandinew** [comment] 2017-02-24 14:30
Hi,
you are right, to build a single segment is for me in this case not a solution.

**Comment by slin30** [comment] 2017-02-24 14:56
I can confirm that this works fine on my end with the following example query:

```{r}
QT <- QueueTrended(reportsuite.id = varList$targSuite, 
                   date.from = "2016-11-01", 
                   date.to = "2017-01-31",
                   metrics = c("uniquevisitors", "visits", "pageviews"),
                   elements = c("evar75", "evar33"),
                   segment.id = c("5515aXXXXXXXXXXXXXXXXXXa", 
                                  "s3000XXXXXXXXXXXXXXXXXXXXXXXXXXXXXb", 
                                  "s3000XXXXXXXXXXXXXXXXXXXXXXXXXXXXX8"),
                   date.granularity = "month",
                   top = c(25, 5)
)
```
Example first row with `dput()`:

```{r}
dput(QT[1,], control = NULL)

list(datetime = list(sec = 0, min = 0, hour = 0, mday = 1, mon = 10, 
    year = 116, wday = 2, yday = 305, isdst = 1, zone = "EDT", 
    gmtoff = NA), evar75 = "::unspecified::", evar33 = "org-user-academic", 
    uniquevisitors = 3200, visits = 4559, pageviews = 13900, 
    segment.id = "5515aXXXXXXXXXXXXXXXXXXa AND s3000XXXXXXXXXXXXXXXXXXXXXXXXXXXXXb AND s3000XXXXXXXXXXXXXXXXXXXXXXXXXXXXX8", 
    segment.name = "Exclude Internal Use ANDExlcude Guest & Promo AND Authenticated Session")
```
Also working fine with different modifications, e.g. date granularity of `day` or a length 1 `top` or even passing `top` as a `character` vector.

**Comment by randyzwitch** [comment] 2017-02-24 15:00
Interesting, thanks for validating @slin30!

@blandinew, which version of RSiteCatalyst are you using? If you're not using the newest version from CRAN, you might try updating, as this might have been reported before and fixed

**Comment by randyzwitch** [comment] 2017-02-24 15:03
Actually, I test for the specific case of multiple segments, so now I'm definitely thinking the error isn't one of implementation but either needed to upgrade the package (or some other weird edge case)

https://github.com/randyzwitch/RSiteCatalyst/blob/master/tests/testthat/test-queuetrended.R#L116-L241

**Comment by michaelstenborg** [comment] 2017-02-24 15:04
I can confirm that the API supports multiple segments for the QueueTrended method (we support this in a C# implementation).

This also works for RSiteCatalyst 1.4.10:

'dfResults <- QueueTrended(reportsuite.id = strSuite,
                         date.from = as.character(Sys.Date()),
                         date.to = as.character(Sys.Date()),
                         metrics = "visits",
                         elements = c(),
                         top = 50000,
                         date.granularity = "hour",
                         segment.id = c("####", "####"),
                         max.attempts = 1440)'

**Comment by randyzwitch** [comment] 2017-02-26 23:50
Since this functionality does appear to be present in newer versions of RSiteCatalyst, I'm going to close this issue. If upgrading the version of RSiteCatalyst doesn't help, please comment on this thread and we can try to figure out what the issue is

**Closed by randyzwitch** 2017-02-26 23:50 UTC
Labels: bug

**Comment by blandinew** [comment] 2017-03-03 14:25
It's working! You had right, I just upgraded the version of RSiteCatalyst and then was everything fine...
Thank you very much for your help!

**Comment by randyzwitch** [comment] 2017-03-03 14:41
Great, glad it's working out for you
